bespoken/dashboard

src/components/Card.test.tsx

Start to add unit test for Card

---

README.md
docs/developer.md
docs/issues.md
package.json
src/actions/session.ts
src/index.tsx
src/models/user.test.ts
src/models/user.ts
src/reducers/session.ts
src/services/auth.ts

Hooked up login workflow to firebase backend.  This closes #2

Firebase Login

---

src/actions/session.test.ts

- Added error condition tests for standard login and github login.
- Added a logout unit test.

Adding an error check and logout test

---

src/actions/authForm.ts
src/actions/session.test.ts
src/actions/session.ts
src/components/AuthForm.test.tsx
src/components/AuthForm.tsx
src/constants/index.ts
src/pages/LoginPage.test.tsx
src/pages/LoginPage.tsx
src/reducers/authForm.ts
src/services/auth.test.ts
src/services/auth.ts

Fixes #3 , Fixes #15 
-Sign up workflow added
-Email check added
-Providing feedback added
@michaelmyers

sign up workflow

---

src/models/source.ts
src/services/source.ts

- New data model to fit the new security requirements.

Updating new model

---

src/pages/LogsPage.tsx

Clear currentSource when Leaving LogsPage

---

src/components/ConversationList/ConversationList.tsx
src/components/ConversationList/ConversationListItem.tsx
src/models/conversation.test.ts
src/models/conversation.ts
src/utils/test.ts

Fixes #80 and handles audio streaming API payloads

Data Fixes

---

src/actions/session.test.ts
src/actions/session.ts
src/reducers/index.test.ts
src/reducers/index.ts

Ensures the state is clear when the user logs out.

Reset State on Logout

---

src/actions/log.ts
src/components/ConversationList/ConversationList.tsx
src/components/ConversationList/ConversationListItem.test.tsx
src/components/ConversationList/ConversationListItem.tsx
src/components/OutputList/OutputList.test.tsx
src/components/OutputList/OutputList.tsx
src/components/OutputList/OutputListItem.test.tsx
src/components/OutputList/OutputListItem.tsx
src/components/OutputList/index.ts
src/constants/index.ts
src/frames/Dashboard.tsx
src/models/conversation.test.ts
src/models/conversation.ts
src/models/log.ts
src/models/output.test.ts
src/models/output.ts
src/pages/LogsPage.tsx
src/utils/test.ts

Fixes #32 and fixes #65 
- New output object for STDOUT information
- Conversation object now has room for STDOUT messages
- Updated styling

STDOUT Display 

---

src/components/SnackBar.tsx
src/components/Snackbar.test.tsx

Unit Test Snackbar

---

.travis.yml
package.json
src/actions/session.ts
src/services/auth.test.ts
src/services/auth.ts
src/services/remote-service.ts
src/store/local-storage.test.ts
src/store/local-storage.ts

- Made a mockable origin for Firebase so classes that use Firebase can be tested.
- Made a mockable origin for localStorage so class that use localStorage can be tested.

Firebase testing

---

src/components/AuthForm.test.tsx
src/components/AuthForm.tsx

Enter for Login with Username and Password

---

package.json
src/components/ConversationListView/ConversationListView.test.tsx
src/components/ConversationListView/ConversationListView.tsx
src/components/Grid/Grid.tsx
src/pages/LogsPage.test.tsx
src/pages/LogsPage.tsx
src/utils/browser.test.ts
src/utils/browser.ts
tsconfig.json
typings/react-list.d.ts

Fixes #64 
- Added an infinite list scroller for recycling elements.
- Fixed padding and clipping on logs page.
- Unregistering listeners on unmounting.

Infinite scroll

---

.vscode/settings.json
package.json
src/components/Interaction.tsx
src/constants/error.ts
src/frames/Dashboard.tsx
src/models/conversation.ts
src/pages/logspage/FilterBar.tsx
src/pages/logspage/FilterableConversationList.tsx
src/pages/logspage/Filters.test.tsx
src/pages/logspage/Filters.tsx
src/pages/logspage/LogsPage.tsx
src/utils/promise.ts
tslint.json

A couple of bug fixes and style updates for pretty-filters

Pixel Pushing

---

src/pages/NewSourcePage.test.tsx
src/pages/NewSourcePage.tsx

Adding unit tests to the new source page.

New source page unit tests

---

src/components/Header.test.tsx
src/components/Header.tsx
src/frames/Dashboard.tsx

Fixes error in selecting sources with the same name.
@michaelmyers

Header fix

---

src/pages/logspage/LogsPage.test.tsx
src/pages/logspage/LogsPage.tsx

Fixes #129 
This was branched off of #127, which should be merged first.

Fix for Infinite Loop

---

src/components/Header.tsx
src/pages/logspage/FilterBar.tsx
src/themes/dropdown-dark-nolabel.scss
src/themes/dropdown.scss

- Dropdown now goes below the text.

Dropdown fix

---

src/actions/session.test.ts
src/actions/session.ts
src/components/List/ListItem.tsx
src/index.tsx
src/pages/LoginPage.tsx
src/pages/SourceListPage.tsx
src/pages/SourcePage.tsx
src/services/auth.ts

Actually fixes #156.
Basic gist:
When logging in, navigation is done in the `index.ts` when a user logged in.  The session.ts is no longer responsible for it. 
Also:
- No longer refreshing page in SourceListPage. Instead it navigates via ReactRouter like it's supposed to.
- Fixed an "undefined" error in ConersationListView.

Authform fix

---

package.json
src/index.tsx
src/pages/logspage/LogsExplorer/LogsExplorer.tsx
src/store/index.ts

Fixes issue in which user is re-routed every time they refresh the page.

Persisting session

---

src/models/conversation.ts

Got some data without requests, this checks it so make sure they exist.

Fix for when a Request Doesn't Exist on a Conversation

---

src/components/ConversationListView/ConversationListViewItem.tsx
src/components/OutputList/StackTraceListItem.tsx
src/components/SourceSummaryView.test.tsx
src/components/SourceSummaryView.tsx
src/models/conversation-list-summary.test.ts
src/models/conversation-list-summary.ts
src/models/conversation.ts
src/models/source-summary.ts
src/models/stack-trace.test.ts

Based on feedback, it is a bit more accurate what we are displaying.

Used "Exception" instead of "Crash"

---

src/components/AuthForm.test.tsx
src/components/Button.test.tsx
src/components/Card.test.tsx
src/components/Content.test.tsx
src/components/ConversationListView/ConversationListView.test.tsx
src/components/ConversationListView/ConversationListViewItem.test.tsx
src/components/Drawer.test.tsx
src/components/FormInput.test.tsx
src/components/Grid/Cell.test.tsx
src/components/Grid/Grid.test.tsx
src/components/Icon/index.test.tsx
src/components/Interaction.test.tsx
src/components/List/List.test.tsx
src/components/NavLink.test.tsx
src/components/Navigation.test.tsx
src/components/Pill.test.tsx
src/components/Ripple/Ripple.test.tsx
src/components/Ripple/RippleContainer.test.tsx
src/components/Snackbar.test.tsx
src/components/UserControl.test.tsx
src/pages/LoginPage.test.tsx
src/pages/NewSourcePage.test.tsx
src/pages/NotFoundPage.test.tsx

Easy one to start off the style alignment milestone
Fixes #181

Remove tslint:disable Rule from Tests

---

src/components/Graphs/Bar/CountChart.test.tsx
src/components/Graphs/Bar/CountChart.tsx
src/components/Graphs/Line/TimeChart.test.tsx
src/components/Graphs/Line/TimeChart.tsx
src/models/conversation.ts
src/models/query.test.ts
src/models/query.ts
src/models/time-series.ts
src/pages/SourcePage.test.tsx
src/pages/SourcePage.tsx
src/pages/logspage/Filters.test.tsx
src/pages/logspage/Filters.tsx
src/pages/logspage/LogsPage.test.tsx
src/services/log.ts
typings/recharts.d.ts

Fixes #135 
- SourcePage now queries all stats data on load.

Quick summary

---

src/pages/logspage/FilterBar/FilterBar.test.tsx
src/pages/logspage/FilterBar/FilterBar.tsx
src/pages/logspage/Filters.test.tsx
src/pages/logspage/Filters.tsx
src/pages/logspage/LogsExplorer/LogsExplorer.tsx
src/themes/checkbox-light.scss
src/themes/checkbox.scss
src/themes/dashboard.scss

Fixes #125
- Added a filter to gather all conversations with exceptions.

Exception filter

---

src/services/log.ts

Setting the endpoint to production so the dashboard can use live data.

Moving endpoint to production

---

src/components/OutputList/OutputList.tsx

Allowing logs to be selectable

---

src/models/conversation.test.ts
src/models/conversation.ts
src/pages/logspage/FilterBar/FilterBar.test.tsx
src/pages/logspage/FilterBar/FilterBar.tsx
src/pages/logspage/Filters.test.tsx
src/pages/logspage/Filters.tsx
src/pages/logspage/LogsExplorer/LogsExplorer.tsx

Fixes #202 
- User can now type different request types in to the box to filter by request.

Ability to Filter by Request Type

---

package.json
src/index.tsx
tsconfig.json
webpack.config.js

Fixes #190
- Adding a strip loader that removes console logs from the code in production

Strip Console Statements

---

package.json
src/components/Interaction.test.tsx
src/components/Interaction.tsx
src/pages/logspage/LogsExplorer/LogsExplorer.tsx
typings/react-json-tree.d.ts

Fixes #218
- The state of the opened JSON tabs are now saved and will remain when user swaps logs as well.

JSON Tree Expand Fix

---

src/components/List/ListItem.tsx
src/models/AlexaConversation.test.ts
src/models/conversation.ts
src/pages/SourceListPage.tsx

Fixes NOTHING
- It now quietly handle situation where request session somehow does not exist on alexa payloads.

Alexa Payloads Without Session Fix

---

README.md

Evaluating Codacy

---

src/actions/log.test.ts
src/actions/log.ts
src/components/ConversationListView/ConversationListView.test.tsx
src/components/ConversationListView/ConversationListView.tsx
src/pages/logspage/LogsExplorer/LogsExplorer.test.tsx
src/pages/logspage/LogsExplorer/LogsExplorer.tsx
src/pages/logspage/LogsPage.test.tsx
src/pages/logspage/LogsPage.tsx

Fixes issue in which the dashboard would just query hundreds of times when it's reached the end.  Also some bindings.

Forever query fix

---

package.json
src/services/remote-service.ts
typings.json
typings/index.d.ts

Fixes Typescript 2.2 typings problem

Typescript 2.2

---

src/components/Graphs/Bar/CountChart.test.tsx
src/components/Graphs/Bar/CountChart.tsx
src/components/Graphs/Line/TimeChart.test.tsx
src/components/Graphs/Line/TimeChart.tsx
src/models/conversation-list.ts
src/models/conversation.ts
src/pages/SourcePage.test.tsx
src/pages/SourcePage.tsx
src/services/log.test.ts
src/services/log.ts
src/utils/colors.ts
typings/recharts.d.ts

Fixes #232 
- Both the time series map and the intent series map will show data for both platforms now.

Google Home Summary Graphs

---

src/models/conversation.ts
src/pages/logspage/filters/ConvoFilters.test.tsx

The conversations now show the correct origin.

Default Origin Fix

---

src/index.tsx
src/models/query.ts
src/pages/sourcepage/DataLoader.test.tsx
src/pages/sourcepage/DataLoader.tsx
src/pages/sourcepage/SourceFullSummary.test.tsx
src/pages/sourcepage/SourceFullSummary.tsx
src/pages/sourcepage/SourceHeader.test.tsx
src/pages/sourcepage/SourceHeader.tsx
src/pages/sourcepage/SourceIntentSummary.test.tsx
src/pages/sourcepage/SourceIntentSummary.tsx
src/pages/sourcepage/SourcePage.test.tsx
src/pages/sourcepage/SourcePage.tsx
src/pages/sourcepage/SourceStats.test.tsx
src/pages/sourcepage/SourceStats.tsx
src/pages/sourcepage/SourceTimeSummary.test.tsx
src/pages/sourcepage/SourceTimeSummary.tsx
src/pages/sourcepage/index.tsx
src/utils/colors.ts

Splitting up the SourcePage to parts and more testing.

Summary Refactor

---

src/pages/sourcepage/SourceFullSummary.test.tsx
src/pages/sourcepage/SourceFullSummary.tsx
src/pages/sourcepage/SourceOriginSelector.test.tsx
src/pages/sourcepage/SourceOriginSelector.tsx
src/pages/sourcepage/SourcePage.test.tsx
src/pages/sourcepage/SourceStats.test.tsx
src/pages/sourcepage/SourceStats.tsx
src/services/log.test.ts
src/services/log.ts

- The stats will now change depending on the items selected in the dashboard.

Stats filter

---

src/models/GoogleHomeConversation.test.ts
src/models/conversation.ts
src/pages/sourcepage/SourceFullSummary.test.tsx

Now using `IntentName` as a fallback in Google conversations

Using action again

---

src/components/AuthForm.test.tsx
src/components/AuthForm.tsx
src/services/auth.ts

Fixes #258 
-The password validation goes through now.

Password fix

---

src/components/Graphs/Bar/CountChart.tsx
typings/recharts.d.ts

Resizing the y-axis of the bar chart so it actually fits.

Fixing formatting

---

src/components/SourceForm.test.tsx
src/components/SourceForm.tsx
src/models/source.test.ts
src/models/source.ts
src/pages/NewSourcePage.tsx
src/services/source.test.ts
src/services/source.ts

Uses new name generating service to generate unique names and secret keys.
Also, fixes issue where sources were not saving the date created.

Name generating service

---

src/pages/integration/IntegrationExpressJS.tsx

Fixes #269
- Adds comments to avoid expressjs miss configuration around body parser.
@chrsdietz

src/pages/integration: expressjs comments

---

src/components/Icon/Icon.tsx
src/components/UserControl.tsx

- Makes width and height props optional on Icon component
- Update user default icon to match GitHub avatar image styling.
Issue: #158 
/cc: @chrsdietz

src/components: improves default avatar ui

---

src/components/AuthForm.tsx
src/components/FormInput.tsx
src/components/Header.test.tsx
src/components/Header.tsx
src/components/Measure.tsx
src/components/OutputList/StackTraceListItem.tsx
src/components/Snackbar.tsx
src/components/SourceForm.tsx
src/components/TwoPane.tsx
src/pages/LoginPage.tsx
src/pages/sourcepage/SourceOriginSelector.test.tsx
src/pages/sourcepage/SourceOriginSelector.tsx

Fixes #180
- No functional changes.  Just no longer binding methods in the render method.

No render bind

---

package.json
src/components/Button.tsx
src/components/Icon/Icon.tsx
src/components/Pill.tsx
src/reducers/auth-form.ts
src/reducers/notification.ts
src/reducers/session.ts
typings.json
typings/index.d.ts

Fixes #122
Fixes #178 
- Removes the Object-assign dependency in favor of the natively supported spread operator.

Object assign

---

src/pages/integration/IntegrationSpokes.tsx

Fixes #392 
-integrationSpokesPage (settings page)

392 refresh settings

---

package.json
src/components/Popup.test.tsx
src/components/Popup.tsx
src/frames/Dashboard.tsx
src/frames/Login.tsx

DO NOT MERGE YET, i still need to add the cookie for hiding the popup if the user already clicked on the contest

Win an echo show popup

---

src/frames/Dashboard.tsx

removes the popup from main page on dashboard

hide popup

---

src/components/Header.tsx

change link

---

src/pages/validation/ValidationPage.tsx
src/themes/input.scss

- Built on top of: #466 
- Closes: #477 
- Merge along with the following PR's:
- https://github.com/bespoken/source-api/pull/45
- https://github.com/bespoken/silent-echo-sdk/pull/40

ValidationPage: enhancements

---

package-lock.json
package.json
src/components/Header.test.tsx
src/components/Header.tsx
src/frames/Dashboard.tsx

Relates #522 
- Header
- Header Test
- Package.json

Landing topbar

---

src/pages/validation/ValidationPage.tsx
src/services/source.test.ts
src/services/source.ts
webpack.config.js

relates #518 
deployment changes for dashboard dev

518 deployment

---

package.json
src/components/SourceSelector/SourceSelectorGlobalStats.tsx
src/components/SourceSelector/SourceSelectorItemComponent.tsx
src/components/SourceSelector/SourceSelectorItemStyle.scss
src/components/SourceSelector/SuccessRadialChart.tsx
src/components/Validation/ValidationParentComponent.tsx
src/pages/validation/ValidationPage.tsx
src/themes/tab_menu_theme.scss

success chart and save script always

---

harness/index.html
webpack.config.js

cache help dev

---

src/components/Graphs/Radial/ValidationRadialChart.tsx
src/components/Graphs/Radial/ValidationRadialChartStyle.scss
src/services/monitoring.ts

change monitor url and radial chart

---

src/pages/integration/IntegrationSpokes.tsx

Add milliseconds label after the milliseconds max Average field

---

src/components/Validation/ValidationComponentGlobalStats.tsx
src/components/Validation/ValidationComponentGlobalStatsStyle.scss
src/pages/validation/ValidationPage.tsx

change message and remove text on right panel
